name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_NAME: github.com/cokemine/ServerStatus-goclient
        run: |-
          docker run \
              --rm \
              --privileged \
              -e GITHUB_TOKEN=${GITHUB_TOKEN} \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v $(pwd):/go/src/${PACKAGE_NAME} \
              -v $(pwd)/sysroot:/sysroot \
              -w /go/src/${PACKAGE_NAME} \
              goreleaser/goreleaser-cross \
              -f .goreleaser_action.yml \
              release --rm-dist 
